# Pull Docker Hub base image
FROM node:16 as build
# Set working directory
WORKDIR /usr/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app to container
COPY . .

# Run production build
RUN npm run build

# production env
FROM nginx:stable
COPY --from=build /usr/app/build /usr/share/nginx/html