version: "3"
services:
  # Client web-server based on https://mindsers.blog/post/https-using-nginx-certbot-docker/
  client-webserver:
    image: nginx:stable
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pacto
    links:
      - server
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - server
    stdin_open: true

  certbot-https-certificate:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - pacto
    depends_on:
      - mongo
    volumes:
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - mongo
    command: /usr/app/node_modules/.bin/nodemon -L src/server.js
    environment:
      - DB_CONNECTION_URL=mongodb://mongo/db
      - TEST_DB_CONNECTION_URL=mongodb://mongo/test

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    networks:
      - pacto
    volumes:
      - mongodb:/data/db

networks:
  pacto:
    driver: bridge

volumes:
  mongodb:
